// Generated by CoffeeScript 1.7.1
(function() {
  var a, colors, force, height, node_data, nodes, svg, tick, width;

  console.log("hello world!");

  width = 960;

  height = 500;

  colors = d3.scale.category10();

  svg = d3.select(".graphedit_canvas").append("svg").attr("width", width).attr("height", height);

  node_data = (function() {
    var _i, _results;
    _results = [];
    for (a = _i = 1; _i <= 10; a = ++_i) {
      _results.push({
        id: a,
        reflexive: false
      });
    }
    return _results;
  })();

  tick = function() {
    nodes.attr("cx", function(d) {
      return d.x;
    });
    return nodes.attr("cy", function(d) {
      return d.y;
    });
  };

  force = d3.layout.force().nodes(node_data).size([width, height]).linkDistance(150).charge(-500).on('tick', tick).start();

  nodes = svg.selectAll(".node").data(node_data).enter().append("circle").attr("class", "node").attr("r", 5).style("fill", function(d) {
    return colors(d.id);
  }).call(force.drag);

  console.log(nodes);

}).call(this);
